class CodeGenConfig
{
    static HotfixNameSpace = "ET";
    static HotfixViewCodeOutputPath = "../../Unity/Codes/HotfixView/Demo/FUI/AutoGeneratedCode/";
    static ModelViewCodeOutputPath = "../../Unity/Codes/ModelView/Demo/FUI/AutoGeneratedCode/"

    // 组件名前缀
    static ClassNamePrefix = "FUI_";

    // 成员名前缀
    static MemberVarNamePrefix = "m_";
}

export { CodeGenConfig };
