"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CodeGenConfig = void 0;
class CodeGenConfig {
    static HotfixNameSpace = "ET";
    static HotfixViewCodeOutputPath = "../../Unity/Codes/HotfixView/Demo/FUI/AutoGeneratedCode/";
    static ModelViewCodeOutputPath = "../../Unity/Codes/ModelView/Demo/FUI/AutoGeneratedCode/";
    // 组件名前缀
    static ClassNamePrefix = "FUI_";
    // 成员名前缀
    static MemberVarNamePrefix = "m_";
}
exports.CodeGenConfig = CodeGenConfig;
