class CodeGenConfig
{
    static ModelViewNameSpace = "ET";
    static HotfixViewNameSpace = "ET";
    static HotfixViewCodeOutputPath = "../../Unity/Codes/HotfixView/Demo/FUI/AutoGeneratedCode/";
    static ModelViewCodeOutputPath = "../../Unity/Codes/ModelView/Demo/FUI/AutoGeneratedCode/";
    static HotfixViewLogicCodeOutputPath = "../../Unity/Codes/HotfixView/Demo/FUI/Logic/";
    static ModelViewLogicCodeOutputPath = "../../Unity/Codes/ModelView/Demo/FUI/Logic/";

    // 组件名前缀
    static ClassNamePrefix = "FUI_";

    static LogicClassNamePrefix = "FUI";

    // 成员名前缀
    static MemberVarNamePrefix = "m_";
}

export { CodeGenConfig };
